In [1]:
# ============================================================
# Assignment Problems
# Q1: IRIS Dataset
# Dataset Link: Iris Flower Dataset
# ============================================================

# A. Display the following information:
#    • First 10 rows
#    • Shape & Data Types
#    • Summary statistics (mean, std, min, max)

# B. Select only those rows where:
#    • petal_length > 4.5
#    • species = "Iris-virginica"

# C. Group by species and compute:
#    • Average sepal_length
#    • Maximum petal_width
#    • Standard deviation of sepal_width

# D. Create a new column:
#    • petal_ratio = petal_length / petal_width
#    • For each species, find the average petal_ratio


# ============================================================
# Q2: TITANIC Dataset
# Dataset Link: Titanic Dataset
# ============================================================

# A. Display only the columns:
#    • Name
#    • Sex
#    • Age
#    • Fare
#    • Survived

# B. Select passengers who:
#    • Are female
#    • Fare > 30

# C. Group by Pclass and compute:
#    • Survival rate
#    • Average Fare
#    • Average Age

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("IRIS.csv")
df.head(10) # First 10 rows

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [6]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [9]:
result = df.groupby('species').agg({
    'sepal_length': 'mean',   # Average sepal_length
    'petal_width': 'max',     # Maximum petal_width
    'sepal_width': 'std'      # Standard deviation of sepal_width
})

print(result)

                 sepal_length  petal_width  sepal_width
species
Iris-setosa             5.006          0.6     0.381024
Iris-versicolor         5.936          1.8     0.313798
Iris-virginica          6.588          2.5     0.322497