# RNN for sentiment analysis for IMDB data

In [58]:
import pandas as pd

In [59]:
df = pd.read_csv("IMDB Dataset.csv")

In [60]:
df.shape

(50000, 2)

In [61]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [62]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [63]:
df.drop_duplicates(inplace=True)

In [64]:
df.shape

(49582, 2)

# Pre Processing

### 1. Converting to Lowercase:

In [65]:
df["review"]= df["review"].str.lower()  # The strings that are available in the DF will be converted to Lowercase

### 2. Removing the URLs

In [66]:
# To perform this action, we use oprn source library of pythom named re (regular expression)

import re

def remove_urls(text):
    text = re.sub(r"http\S+", "" , text)  # (pattern, replacement, string)
    return text
             # \S -> Non whitespace characters after the text (capital S)
             # \s -> whitespace character

df["review"] = df["review"].apply(remove_urls)

### 3. Remove punctuations:

In [67]:
# We will consider the values as punctuations that does not comes under the range A-Z a-z 0-9 and \s (space)
def remove_punctuations(text):
    text = re.sub(r"^[A-Za-z0-9\s]", "" , text) # ^ means include
    return text

df["review"] = df["review"].apply(remove_punctuations)

### 4, Removing HTML tags

In [68]:
# Some symbols in RegEx:
# . -> any character
# * -> 0 or more character

def remove_html(text):
    text = re.sub(r"<.*?>", "" , text)
    return text

df["review"] = df["review"].apply(remove_html)

### 5. Remove Stopwords

In [69]:
import nltk

In [70]:
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [71]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [72]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text = text.replace(word, "")

    return text

df["review"] = df["review"].apply(remove_stopwords)

In [73]:
df.head()

                                              review sentiment
0  ne    revewers  nted   wtchg  1 oz epode 'll  ...  positive
1   wderful ltle producti.  filming technique   u...  positive
2   thought    wderful wy  spend tme   o hot summ...  positive
3  sclly 's  fmly   lttle boy (jke) thks 's  zomb...  negative
4  etter mttei's "love   time  mey"   vully stunn...  positive