# RNN for sentiment analysis for IMDB data

In [9]:
import pandas as pd

In [10]:
df = pd.read_csv("/IMDB Dataset.csv")

In [11]:
df.shape

(50000, 2)

In [12]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [13]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [14]:
df.drop_duplicates(inplace=True)

In [15]:
df.shape

(49582, 2)

# Pre Processing

### 1. Converting to Lowercase:

In [16]:
df["review"]= df["review"].str.lower()  # The strings that are available in the DF will be converted to Lowercase

### 2. Removing the URLs

In [17]:
# To perform this action, we use oprn source library of pythom named re (regular expression)

import re

def remove_urls(text):
    text = re.sub(r"http\S+", "" , text)  # (pattern, replacement, string)
    return text
             # \S -> Non whitespace characters after the text (capital S)
             # \s -> whitespace character

df["review"] = df["review"].apply(remove_urls)

### 3. Remove punctuations:

In [18]:
# We will consider the values as punctuations that does not comes under the range A-Z a-z 0-9 and \s (space)
def remove_punctuations(text):
    text = re.sub(r"^[A-Za-z0-9\s]", "" , text) # ^ means include
    return text

df["review"] = df["review"].apply(remove_punctuations)

### 4, Removing HTML tags

In [19]:
# Some symbols in RegEx:
# . -> any character
# * -> 0 or more character

def remove_html(text):
    text = re.sub(r"<.*?>", "" , text)
    return text

df["review"] = df["review"].apply(remove_html)

### 5. Remove Stopwords

In [20]:
import nltk

In [21]:
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [22]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [23]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text = text.replace(word, "")

    return text

df["review"] = df["review"].apply(remove_stopwords)

In [24]:
df.head()

                                              review sentiment
0  ne    revewers  nted   wtchg  1 oz epode 'll  ...  positive
1   wderful ltle producti.  filming technique   u...  positive
2   thought    wderful wy  spend tme   o hot summ...  positive
3  sclly 's  fmly   lttle boy (jke) thks 's  zomb...  negative
4  etter mttei's "love   time  mey"   vully stunn...  positive

### 6. Stemming

In [26]:
# Converting words to their base form using very famous algorithm - potter stemming

from nltk.stem import PorterStemmer

def stemming(text):
    stemmer = PorterStemmer()
    stemmed_words = []

    tokens = word_tokenize(text)

    for word in tokens:
        stemmed_word = stemmer.stem(word)
        stemmed_words.append(stemmed_word)

    return " ".join(stemmed_words)


df["review"] = df["review"].apply(stemming)

### 7. Encoding

In [31]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["sentiment"] = le.fit_transform(df["sentiment"])

In [32]:
y= df["sentiment"]

In [33]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

### 8. Vectorization

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

TfidfVectorizer(max_features=2500)